version: "3.12"
services:
  db:
    container_name: db
    image: postgres:16.2
    environment:
      - POSTGRES_DB=mantella
      - POSTGRES_USER=mantella
      - POSTGRES_PASSWORD=mantella123321
    ports:
      - 5432:5432
  api:
    restart: on-failure
    depends_on:
      - db
    container_name: api
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8000
